### ISSUE TITLE
cannot upload figures

### ISSUE THREAD

**Issue by stokkumrmv** [dualslash/The-FAIR-Handbook#1]
cannot upload figures for sections pet2 and pet3.

**Comment by dualslash** [comment]
The linkage in the figure was incorrect, I resolved this for [pet2](https://raw.githubusercontent.com/dualslash/The-FAIR-Handbook/main/The-FAIR-Handbook/pet2.md) which you can see in this raw view. I haven't been able to find the image [./_static/img/fl_efro.png](https://github.com/dualslash/The-FAIR-Handbook/blob/main/The-FAIR-Handbook/_static/img/fl_efro.png) for pet3 so I cannot resolve it for that page.

**Comment by stokkumrmv** [comment]
It was a bug on my end, but it solved itself after clearing cookies in the browser.

**Comment by stokkumrmv** [comment]
> The linkage in the figure was incorrect, I resolved this for [pet2](https://raw.githubusercontent.com/dualslash/The-FAIR-Handbook/main/The-FAIR-Handbook/pet2.md) which you can see in this raw view. I haven't been able to find the image [./_static/img/fl_efro.png](https://github.com/dualslash/The-FAIR-Handbook/blob/main/The-FAIR-Handbook/_static/img/fl_efro.png) for pet3 so I cannot resolve it for that page.

Yeah that was the issue, uploading the files :)
