### ISSUE TITLE
create conclusion for PET chapter 

### ISSUE THREAD

**Issue by stokkumrmv** [dualslash/The-FAIR-Handbook#2]
I would like to add a paragraph to the Model-to-data chapter (so a file called pet5.md) with the following text:
@dualslash can you help me out?

# Concluding remarks and variations of the techniques and solutions
Every of these hereabove described techniques and solutions partially solves the privacy challenges, which are put by the EU and national regulations and user requirements. The solutions are chosen depending on the needs and specific requests from the individual use-cases. In many cases a potential solution lays in applying a chosen mix of different techniques.  This section is dedicated to the comparison of different available solutions and techniques in order to help to choose a correct combination for a specific case.
The solutions can be separated into 3 different layers. For every layer one or more techniques could/should be chosen to guarantee in the end specified requested level of privacy. 
The layers and techniques related to that layers are presented at a figure below.

```{figure} ../images/esas_efro.png
---
height: 150px
name: esas-efro
---
Techniques and layers making up a health data ecosystem.
```

The choices coming from the different use-cases should cover all three layers: platform, algorithm security and privacy-enhancing techniques. In the end there should be the choice of one platform, possibly one or more solutions from algorithmic side, and this solution should be combined with the chosen one or more privacy-enhancing techniques.
In some cases there are ready implementations of some algorithms and usage of specific PET techniques on specific platform. That allows anybody to make an easier choice on a specific Ecosystem as a service (EaaS) where all layers are covered by existing toolsets. However, sometimes these solutions are not suited for specific use-case, therefore, such ecosystems should be evaluated before applying them in practice against the requirements coming from the use-case.
FAIR standardization effort makes the choices easier by taking in consideration the needed interfaces and policies around data and models that could be needed.

**Comment by dualslash** [comment]
This has been added, although I do not have the image that you want to add. Could you attach or upload this? Same for pet3.

**Comment by stokkumrmv** [comment]
Done! Thanks!
